---
- hosts: all
  serial: 1
  sudo: yes
  pre_tasks:
    - include: check_git_synced.yml
      sudo: no
      when: no_safety_features is undefined
    - pause: prompt="Deploying backend ({{atlas_git_version}}) and frontend ({{atlas_frontend_git_version}}) to {{ansible_ssh_host}} with environment type {{atlas_environment}}. Ctrl+C to cancel!"
      when: no_safety_features is undefined
  roles:
    - role: nodesource.node
    - role: frontend-build
      when: no_frontend is undefined
    - role: web
  post_tasks:
    - name: Send notification message via Slack
      local_action:
        module: slack
        domain: cid-harvard.slack.com
        token: "{{ atlas_slack_token }}"
        msg: "Deployed backend ({{ atlas_git_version }}) and frontend ({{atlas_frontend_git_version}}) to {{ ansible_ssh_host }} with environment type {{atlas_environment}}."
      sudo: no
      when: atlas_environment == 'prod' and atlas_slack_token is defined
