---
- include: system.yml
- include: frontend.yml
  when: no_frontend is undefined
- include: backend.yml
- name: Send notification message via Slack
  local_action:
    module: slack
    domain: cid-harvard.slack.com
    token: "{{ atlas_slack_token }}"
    msg: "Deployed backend ({{ atlas_git_version }}) and frontend ({{atlas_frontend_git_version}}) to {{ ansible_ssh_host }} with environment type {{atlas_environment}}."
  sudo: no
  when: atlas_environment == 'prod'
